# Generated by Django 5.0.6 on 2024-06-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bandqilish_comand_login_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='comand',
            name='name1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comand',
            name='name2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comand',
            name='name3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comand',
            name='name4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
